#!/usr/bin/env node
// packaging/generate.mjs
//
// GENERATED-FILE GENERATOR. This script is the ONLY writer of:
//   .claude-plugin/marketplace.json                          (repo root — Claude Code marketplace discovery)
//   .agents/plugins/marketplace.json                          (repo root — documented Codex marketplace discovery path)
//   cortadel-plugin/.claude-plugin/plugin.json                (Claude Code plugin manifest — full: userConfig + inline mcpServers)
//   cortadel-plugin/.codex-plugin/plugin.json                 (Codex plugin manifest — skills-only)
//
// Source of truth: packaging/plugin.metadata.json — the only hand-written place for plugin
// identity (name, displayName, version, description, author, homepage, repository, license,
// keywords, category, pluginDir), the four userConfig options, and the MCP URL template.
//
// Never hand-edit any of the four generated files above. If output is wrong, fix
// plugin.metadata.json or this generator, then re-run:
//
//   node packaging/generate.mjs
//
// Why the generated JSON files carry no embedded "generated by" marker (unlike this file, which
// is not itself generated): JSON has no comment syntax, and `claude plugin validate --strict`
// rejects ANY unrecognized field anywhere in plugin.json/marketplace.json — verified empirically:
// a top-level "_generated" string and a "metadata.generated" key both fail --strict with
// "Unknown field". Embedding a provenance marker would break the very CI gate this packaging
// system exists to pass. This header plus packaging/test/ (which pins the generated output back
// to this source) are the provenance trail instead — see packaging/test/generate.test.mjs.
//
// Zero dependencies: Node 18+ built-in fs/path/url only, matching the plugin itself.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');

export const METADATA_PATH = path.join(HERE, 'plugin.metadata.json');
const PLUGIN_DIR_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

const OPTION_KEY_RE = /^[A-Za-z_]\w*$/;
const ALLOWED_OPTION_KEYS = new Set([
  'type',
  'title',
  'description',
  'default',
  'required',
  'sensitive',
  'multiple',
  'min',
  'max',
]);
const REQUIRED_OPTION_KEYS = ['type', 'title', 'description'];
const USER_CONFIG_PLACEHOLDER_RE = /\$\{user_config\.([A-Za-z_]\w*)\}/g;

/** Load and structurally validate packaging/plugin.metadata.json. Throws on any violation. */
export function loadMetadata(metadataPath = METADATA_PATH) {
  const meta = JSON.parse(readFileSync(metadataPath, 'utf8'));

  if (typeof meta.pluginDir !== 'string' || !PLUGIN_DIR_RE.test(meta.pluginDir)) {
    throw new Error(
      `plugin.metadata.json: pluginDir must be a kebab-case directory name matching ${PLUGIN_DIR_RE}, got ${JSON.stringify(meta.pluginDir)}`
    );
  }

  for (const [key, opt] of Object.entries(meta.userConfig)) {
    if (!OPTION_KEY_RE.test(key)) {
      throw new Error(`plugin.metadata.json: userConfig key "${key}" must match ${OPTION_KEY_RE}`);
    }
    for (const required of REQUIRED_OPTION_KEYS) {
      if (!(required in opt)) {
        throw new Error(`plugin.metadata.json: userConfig.${key} is missing required "${required}"`);
      }
    }
    for (const k of Object.keys(opt)) {
      if (!ALLOWED_OPTION_KEYS.has(k)) {
        throw new Error(`plugin.metadata.json: userConfig.${key} has disallowed key "${k}"`);
      }
    }
  }

  const declaredKeys = new Set(Object.keys(meta.userConfig));
  for (const m of meta.mcp.urlTemplate.matchAll(USER_CONFIG_PLACEHOLDER_RE)) {
    if (!declaredKeys.has(m[1])) {
      throw new Error(`plugin.metadata.json: mcp.urlTemplate references undeclared user_config key "${m[1]}"`);
    }
  }

  return meta;
}

/** The inline mcpServers block shared by every consumer that needs it (Claude Code plugin.json). */
export function buildMcpServers(meta) {
  return {
    [meta.mcp.serverName]: {
      type: 'http',
      url: meta.mcp.urlTemplate,
      headers: { Authorization: 'Bearer ${user_config.api_key}' },
    },
  };
}

/** Full Claude Code plugin manifest: identity + userConfig + inline mcpServers. */
export function buildClaudePluginJson(meta) {
  return {
    name: meta.name,
    description: meta.description,
    version: meta.version,
    author: meta.author,
    homepage: meta.homepage,
    repository: meta.repository,
    license: meta.license,
    keywords: meta.keywords,
    userConfig: meta.userConfig,
    mcpServers: buildMcpServers(meta),
  };
}

/**
 * Codex plugin manifest — skills-only by owner decision. Codex's plugin format has no
 * user-config templating mechanism (no `${user_config.*}`-style substitution), so it cannot
 * express a self-hosted base URL with a per-user path segment the way Claude Code's inline
 * mcpServers can. Shipping an mcpServers/userConfig block here would silently not work, so this
 * manifest carries the skill only — no mcpServers, no hooks, no userConfig.
 */
export function buildCodexPluginJson(meta) {
  return {
    name: meta.name,
    description: meta.description,
    version: meta.version,
    author: meta.author,
    homepage: meta.homepage,
    repository: meta.repository,
    license: meta.license,
    keywords: meta.keywords,
    skills: './skills/',
  };
}

/**
 * Marketplace entry for the plugin. Deliberately carries NO `version`: plugin.json's version is
 * the single source of truth for version resolution (Claude Code's documented resolution order
 * takes plugin.json's version first when both are set), so a marketplace-side duplicate could
 * only ever drift out of sync with it — see packaging/test/generate.test.mjs, which asserts
 * `version` never reappears in a marketplace entry.
 */
export function buildMarketplaceEntry(meta) {
  return {
    name: meta.name,
    source: `./${meta.pluginDir}`,
    description: meta.description,
    author: meta.author,
    homepage: meta.homepage,
    repository: meta.repository,
    license: meta.license,
    keywords: meta.keywords,
    category: meta.category,
  };
}

/** One marketplace manifest, shared verbatim by both the Claude Code and Codex discovery paths. */
export function buildMarketplaceJson(meta) {
  return {
    name: 'cortadel',
    owner: { name: meta.author.name, url: meta.homepage },
    metadata: { description: meta.description },
    plugins: [buildMarketplaceEntry(meta)],
  };
}

function writeJson(filePath, obj) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, JSON.stringify(obj, null, 2) + '\n', 'utf8');
  return filePath;
}

export function outputPaths(root = ROOT, meta = loadMetadata()) {
  return {
    claudeMarketplace: path.join(root, '.claude-plugin', 'marketplace.json'),
    codexMarketplace: path.join(root, '.agents', 'plugins', 'marketplace.json'),
    claudePlugin: path.join(root, meta.pluginDir, '.claude-plugin', 'plugin.json'),
    codexPlugin: path.join(root, meta.pluginDir, '.codex-plugin', 'plugin.json'),
  };
}

export function generate({ root = ROOT, metadataPath = METADATA_PATH, log = () => {} } = {}) {
  const meta = loadMetadata(metadataPath);
  const paths = outputPaths(root, meta);
  const marketplace = buildMarketplaceJson(meta);

  const written = [
    writeJson(paths.claudeMarketplace, marketplace),
    writeJson(paths.codexMarketplace, marketplace),
    writeJson(paths.claudePlugin, buildClaudePluginJson(meta)),
    writeJson(paths.codexPlugin, buildCodexPluginJson(meta)),
  ];
  for (const f of written) log(`wrote ${path.relative(root, f)}`);
  return written;
}

// Only run when executed directly (`node packaging/generate.mjs`) — not when imported by tests.
if (path.resolve(fileURLToPath(import.meta.url)) === path.resolve(process.argv[1] ?? '')) {
  generate({ log: (line) => console.log(line) });
  console.log('done.');
}
