// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  site: 'https://docs.cortadel.com',
  integrations: [
    starlight({
      title: 'Cortadel',
      description:
        'Self-hosted long-term temporal graph memory for AI agents — MCP, REST and a dashboard in one container.',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/cortadel/cortadel' },
      ],
      editLink: { baseUrl: 'https://github.com/cortadel/cortadel/edit/main/website/' },
      sidebar: [
        {
          label: 'Start here',
          items: [
            { label: 'Getting started', slug: 'getting-started' },
            { label: 'Self-hosting the server', slug: 'self-hosting' },
            { label: 'Authentication', slug: 'authentication' },
          ],
        },
        {
          label: 'Integrate',
          items: [
            { label: 'MCP integration', slug: 'mcp' },
            { label: 'Claude Code & Codex plugin', slug: 'plugin' },
            { label: '.NET SDK reference', slug: 'sdk-dotnet' },
            { label: 'Python SDK reference', slug: 'sdk-python' },
            { label: 'TypeScript SDK reference', slug: 'sdk-typescript' },
          ],
        },
        // The twelve framework integrations, plus the index page they all link back to.
        //
        // An explicit list rather than `autogenerate: { directory: 'integrations' }`, for three
        // reasons that autogenerate cannot satisfy from this file:
        //
        //  1. Order. Autogenerate sorts by slug, which interleaves the languages (CrewAI, a Python
        //     package, would land second). Every other listing of these twelve — the docs index
        //     table, the root README, integrations/README.md — is grouped TypeScript → Python →
        //     .NET, and this sidebar matches that order so the four lists agree. Reordering an
        //     autogenerated group needs a `sidebar.order` field in each page's frontmatter, i.e.
        //     twelve edits in the content tree to express one decision that belongs here.
        //  2. The index page. `integrations.md` sits at the docs root (Starlight routes it to
        //     /integrations/), not inside the `integrations/` directory, so autogenerate would
        //     leave it out and the group would need a hand-written entry anyway.
        //  3. Build-time checking. A slug listed here that does not resolve to a real content entry
        //     throws an AstroError and fails the build, so a renamed or deleted page cannot quietly
        //     become an orphan.
        //
        // The entries deliberately carry no `label`: Starlight falls back to the page's own
        // frontmatter `title` (`sidebar.label` first, if a page ever sets one). The groups above
        // spell their labels out, but every one of those is byte-identical to its page's title —
        // so omitting the label here keeps the same rendered result while removing the copy that
        // could drift out of sync with a page this file does not own.
        {
          label: 'Framework integrations',
          items: [
            { slug: 'integrations' },
            // TypeScript (8)
            { slug: 'integrations/claude-agent-sdk' },
            { slug: 'integrations/deepagents' },
            { slug: 'integrations/langgraph' },
            { slug: 'integrations/mastra' },
            { slug: 'integrations/n8n-nodes-cortadel' },
            { slug: 'integrations/openai-agents' },
            { slug: 'integrations/openclaw' },
            { slug: 'integrations/vercel-ai-sdk' },
            // Python (3)
            { slug: 'integrations/crewai' },
            { slug: 'integrations/google-adk' },
            { slug: 'integrations/pydantic-ai' },
            // .NET (1)
            { slug: 'integrations/microsoft-agent-framework' },
          ],
        },
      ],
    }),
  ],
});
